//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.20 at 03:19:39 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.geni.net/resources/rspec/3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package be.iminds.ilabt.jfed.rspec.manifest.geni_rspec_3;
