package be.iminds.ilabt.jfed.lowlevel;

/**
 * ApiMethodParameterType
 */
public enum ApiMethodParameterType {
    NOT_SPECIFIED,
    STRING,
    STRING_MULTILINE,
    INTEGER,
    BOOLEAN,
    CREDENTIAL_STRING,
    USER_CREDENTIAL_STRING,
    SLICE_CREDENTIAL_STRING,
    URN,
    SLICE_URN,
    USER_URN,
    RSPEC_STRING,
    LIST_OF_STRING,
    LIST_OF_CREDENTIAL,
    LIST_OF_URN_STRING,
    LIST_OF_SLICE_URN_STRING,
    LIST_OF_USER_URN_STRING,
    LIST_OF_URN,
    LIST_OF_SLICE_URN,
    LIST_OF_USER_URN,
    LIST_OF_USERSPEC,
    MAP_OF_STRING_TO_OBJECT,
    MAP_OF_STRING_TO_STRING,
    GENI_EXTRA_OPTIONS,
    CH_API_FILTER,
    CH_API_MATCH,
    CH_API_FIELDS,
    CH_API_LIST_MEMBER_TUPLES
}
