//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.05 at 02:08:08 PM CEST 
//


package be.iminds.ilabt.jfed.lowlevel.authority.binding;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="authority" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="urn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="hrn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="urls">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="serverurl" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="servertype">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="role">
 *                                                 &lt;simpleType>
 *                                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                     &lt;enumeration value="Slice Authority"/>
 *                                                     &lt;enumeration value="Aggregate Manager"/>
 *                                                     &lt;enumeration value="PlanetLab registry"/>
 *                                                   &lt;/restriction>
 *                                                 &lt;/simpleType>
 *                                               &lt;/attribute>
 *                                               &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="type">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Clearinghouse"/>
 *                         &lt;enumeration value="Builtin"/>
 *                         &lt;enumeration value="User"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="gid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="reconnectEachTime" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="pemSslTrustCert" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="allowedCertificateHostnameAliases">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="alias" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authority"
})
@XmlRootElement(name = "authorities")
public class Authorities {

    @XmlElement(required = true)
    protected List<Authorities.Authority> authority;

    /**
     * Gets the value of the authority property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authority property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthority().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Authorities.Authority }
     * 
     * 
     */
    public List<Authorities.Authority> getAuthority() {
        if (authority == null) {
            authority = new ArrayList<Authorities.Authority>();
        }
        return this.authority;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="urn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="hrn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="urls">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="serverurl" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="servertype">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;attribute name="role">
     *                                       &lt;simpleType>
     *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                           &lt;enumeration value="Slice Authority"/>
     *                                           &lt;enumeration value="Aggregate Manager"/>
     *                                           &lt;enumeration value="PlanetLab registry"/>
     *                                         &lt;/restriction>
     *                                       &lt;/simpleType>
     *                                     &lt;/attribute>
     *                                     &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="type">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Clearinghouse"/>
     *               &lt;enumeration value="Builtin"/>
     *               &lt;enumeration value="User"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="gid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="reconnectEachTime" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="pemSslTrustCert" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="allowedCertificateHostnameAliases">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="alias" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    @XmlRootElement(name = "authority")
    public static class Authority {

        @XmlElement(required = true)
        protected String urn;
        @XmlElement(required = true)
        protected String hrn;
        @XmlElement(required = true)
        protected Authorities.Authority.Urls urls;
        @XmlElement(required = true)
        protected String type;
        @XmlElement(required = true)
        protected String gid;
        @XmlElement(required = true)
        protected String source;
        protected boolean reconnectEachTime;
        @XmlElement(required = true)
        protected String pemSslTrustCert;
        @XmlElement(required = true)
        protected Authorities.Authority.AllowedCertificateHostnameAliases allowedCertificateHostnameAliases;

        /**
         * Gets the value of the urn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUrn() {
            return urn;
        }

        /**
         * Sets the value of the urn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUrn(String value) {
            this.urn = value;
        }

        /**
         * Gets the value of the hrn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHrn() {
            return hrn;
        }

        /**
         * Sets the value of the hrn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHrn(String value) {
            this.hrn = value;
        }

        /**
         * Gets the value of the urls property.
         * 
         * @return
         *     possible object is
         *     {@link Authorities.Authority.Urls }
         *     
         */
        public Authorities.Authority.Urls getUrls() {
            return urls;
        }

        /**
         * Sets the value of the urls property.
         * 
         * @param value
         *     allowed object is
         *     {@link Authorities.Authority.Urls }
         *     
         */
        public void setUrls(Authorities.Authority.Urls value) {
            this.urls = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the gid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGid() {
            return gid;
        }

        /**
         * Sets the value of the gid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGid(String value) {
            this.gid = value;
        }

        /**
         * Gets the value of the source property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSource() {
            return source;
        }

        /**
         * Sets the value of the source property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSource(String value) {
            this.source = value;
        }

        /**
         * Gets the value of the reconnectEachTime property.
         * 
         */
        public boolean isReconnectEachTime() {
            return reconnectEachTime;
        }

        /**
         * Sets the value of the reconnectEachTime property.
         * 
         */
        public void setReconnectEachTime(boolean value) {
            this.reconnectEachTime = value;
        }

        /**
         * Gets the value of the pemSslTrustCert property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPemSslTrustCert() {
            return pemSslTrustCert;
        }

        /**
         * Sets the value of the pemSslTrustCert property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPemSslTrustCert(String value) {
            this.pemSslTrustCert = value;
        }

        /**
         * Gets the value of the allowedCertificateHostnameAliases property.
         * 
         * @return
         *     possible object is
         *     {@link Authorities.Authority.AllowedCertificateHostnameAliases }
         *     
         */
        public Authorities.Authority.AllowedCertificateHostnameAliases getAllowedCertificateHostnameAliases() {
            return allowedCertificateHostnameAliases;
        }

        /**
         * Sets the value of the allowedCertificateHostnameAliases property.
         * 
         * @param value
         *     allowed object is
         *     {@link Authorities.Authority.AllowedCertificateHostnameAliases }
         *     
         */
        public void setAllowedCertificateHostnameAliases(Authorities.Authority.AllowedCertificateHostnameAliases value) {
            this.allowedCertificateHostnameAliases = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="alias" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "alias"
        })
        public static class AllowedCertificateHostnameAliases {

            @XmlElement(required = true)
            protected List<String> alias;

            /**
             * Gets the value of the alias property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the alias property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAlias().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getAlias() {
                if (alias == null) {
                    alias = new ArrayList<String>();
                }
                return this.alias;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="serverurl" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="servertype">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;attribute name="role">
         *                             &lt;simpleType>
         *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                                 &lt;enumeration value="Slice Authority"/>
         *                                 &lt;enumeration value="Aggregate Manager"/>
         *                                 &lt;enumeration value="PlanetLab registry"/>
         *                               &lt;/restriction>
         *                             &lt;/simpleType>
         *                           &lt;/attribute>
         *                           &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "serverurl"
        })
        public static class Urls {

            @XmlElement(required = true)
            protected List<Authorities.Authority.Urls.Serverurl> serverurl;

            /**
             * Gets the value of the serverurl property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the serverurl property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getServerurl().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Authorities.Authority.Urls.Serverurl }
             * 
             * 
             */
            public List<Authorities.Authority.Urls.Serverurl> getServerurl() {
                if (serverurl == null) {
                    serverurl = new ArrayList<Authorities.Authority.Urls.Serverurl>();
                }
                return this.serverurl;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="servertype">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;attribute name="role">
             *                   &lt;simpleType>
             *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *                       &lt;enumeration value="Slice Authority"/>
             *                       &lt;enumeration value="Aggregate Manager"/>
             *                       &lt;enumeration value="PlanetLab registry"/>
             *                     &lt;/restriction>
             *                   &lt;/simpleType>
             *                 &lt;/attribute>
             *                 &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "servertype",
                "url"
            })
            public static class Serverurl {

                @XmlElement(required = true)
                protected Authorities.Authority.Urls.Serverurl.Servertype servertype;
                @XmlElement(required = true)
                protected String url;

                /**
                 * Gets the value of the servertype property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Authorities.Authority.Urls.Serverurl.Servertype }
                 *     
                 */
                public Authorities.Authority.Urls.Serverurl.Servertype getServertype() {
                    return servertype;
                }

                /**
                 * Sets the value of the servertype property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Authorities.Authority.Urls.Serverurl.Servertype }
                 *     
                 */
                public void setServertype(Authorities.Authority.Urls.Serverurl.Servertype value) {
                    this.servertype = value;
                }

                /**
                 * Gets the value of the url property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUrl() {
                    return url;
                }

                /**
                 * Sets the value of the url property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUrl(String value) {
                    this.url = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;attribute name="role">
                 *         &lt;simpleType>
                 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                 *             &lt;enumeration value="Slice Authority"/>
                 *             &lt;enumeration value="Aggregate Manager"/>
                 *             &lt;enumeration value="PlanetLab registry"/>
                 *           &lt;/restriction>
                 *         &lt;/simpleType>
                 *       &lt;/attribute>
                 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Servertype {

                    @XmlAttribute
                    protected String role;
                    @XmlAttribute
                    protected String version;

                    /**
                     * Gets the value of the role property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getRole() {
                        return role;
                    }

                    /**
                     * Sets the value of the role property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setRole(String value) {
                        this.role = value;
                    }

                    /**
                     * Gets the value of the version property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getVersion() {
                        return version;
                    }

                    /**
                     * Sets the value of the version property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setVersion(String value) {
                        this.version = value;
                    }

                }

            }

        }

    }

}
