//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.05 at 02:08:08 PM CEST 
//


package be.iminds.ilabt.jfed.lowlevel.authority.binding;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the be.iminds.ilabt.jfed.lowlevel.authority.binding package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: be.iminds.ilabt.jfed.lowlevel.authority.binding
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Authorities.Authority.Urls }
     * 
     */
    public Authorities.Authority.Urls createAuthoritiesAuthorityUrls() {
        return new Authorities.Authority.Urls();
    }

    /**
     * Create an instance of {@link Authorities.Authority.Urls.Serverurl }
     * 
     */
    public Authorities.Authority.Urls.Serverurl createAuthoritiesAuthorityUrlsServerurl() {
        return new Authorities.Authority.Urls.Serverurl();
    }

    /**
     * Create an instance of {@link Authorities.Authority }
     * 
     */
    public Authorities.Authority createAuthoritiesAuthority() {
        return new Authorities.Authority();
    }

    /**
     * Create an instance of {@link Authorities.Authority.AllowedCertificateHostnameAliases }
     * 
     */
    public Authorities.Authority.AllowedCertificateHostnameAliases createAuthoritiesAuthorityAllowedCertificateHostnameAliases() {
        return new Authorities.Authority.AllowedCertificateHostnameAliases();
    }

    /**
     * Create an instance of {@link Authorities.Authority.Urls.Serverurl.Servertype }
     * 
     */
    public Authorities.Authority.Urls.Serverurl.Servertype createAuthoritiesAuthorityUrlsServerurlServertype() {
        return new Authorities.Authority.Urls.Serverurl.Servertype();
    }

    /**
     * Create an instance of {@link be.iminds.ilabt.jfed.lowlevel.authority.binding.Servertype }
     * 
     */
    public be.iminds.ilabt.jfed.lowlevel.authority.binding.Servertype createServertype() {
        return new be.iminds.ilabt.jfed.lowlevel.authority.binding.Servertype();
    }

    /**
     * Create an instance of {@link Authorities }
     * 
     */
    public Authorities createAuthorities() {
        return new Authorities();
    }

}
