//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.05 at 02:08:08 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://jfed.iminds.be/authority", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package be.iminds.ilabt.jfed.lowlevel.authority.binding;
