//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.20 at 04:22:13 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.geni.net/resources/rspec/3"
        , xmlns = {
                    @javax.xml.bind.annotation.XmlNs(prefix = "", namespaceURI = "http://www.geni.net/resources/rspec/3") }
        , elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package be.iminds.ilabt.jfed.rspec.request.geni_rspec_3;
