//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.20 at 03:35:58 PM CET 
//


package be.iminds.ilabt.jfed.rspec.request.geni_rspec_2;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for ServiceContents complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceContents">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;choice>
 *           &lt;group ref="{http://www.protogeni.net/resources/rspec/2}AnyExtension"/>
 *           &lt;element ref="{http://www.protogeni.net/resources/rspec/2}login"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element ref="{http://www.protogeni.net/resources/rspec/2}install"/>
 *           &lt;element ref="{http://www.protogeni.net/resources/rspec/2}execute"/>
 *         &lt;/choice>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://www.protogeni.net/resources/rspec/2}AnyExtension"/>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceContents", propOrder = {
    "anyOrLoginOrInstall"
})
public class ServiceContents {

    @XmlElementRefs({
        @XmlElementRef(name = "login", namespace = "http://www.protogeni.net/resources/rspec/2", type = JAXBElement.class),
        @XmlElementRef(name = "install", namespace = "http://www.protogeni.net/resources/rspec/2", type = JAXBElement.class),
        @XmlElementRef(name = "execute", namespace = "http://www.protogeni.net/resources/rspec/2", type = JAXBElement.class)
    })
    @XmlAnyElement(lax = true)
    protected List<Object> anyOrLoginOrInstall;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the anyOrLoginOrInstall property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anyOrLoginOrInstall property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnyOrLoginOrInstall().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link org.w3c.dom.Element }
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link be.iminds.ilabt.jfed.rspec.request.geni_rspec_2.ExecuteServiceContents }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link be.iminds.ilabt.jfed.rspec.request.geni_rspec_2.LoginServiceContents }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link be.iminds.ilabt.jfed.rspec.request.geni_rspec_2.InstallServiceContents }{@code >}
     * 
     * 
     */
    public List<Object> getAnyOrLoginOrInstall() {
        if (anyOrLoginOrInstall == null) {
            anyOrLoginOrInstall = new ArrayList<Object>();
        }
        return this.anyOrLoginOrInstall;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
