//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.06 at 03:04:43 PM CEST 
//

//changed by wvdemeer to add jFed prefered prefix
@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://jfed.iminds.be/rspec/ext/jfed/1"
        , xmlns = {
            @javax.xml.bind.annotation.XmlNs(prefix = "jFed", namespaceURI = "http://jfed.iminds.be/rspec/ext/jfed/1") }
        , elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package be.iminds.ilabt.jfed.ui.rspeceditor.rspec_ext.binding;
